use_frameworks!

platform :ios, '13.0'

target 'Go23WalletCore_Example' do
  pod 'Go23WalletCore', :path => '../'

  target 'Go23WalletCore_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
